name: Schedule

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        default: "master"
  schedule:
    - cron: 0 23 * * *

jobs:
  schedule:
    uses: Geode-solutions/actions/.github/workflows/cpp-schedule.yml@master
    with:
      name: OPENGEODE
      directory: opengeode
      branch: ${{ inputs.branch || 'next' }}
    secrets: 
      TOKEN: ${{ secrets.TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
