name: Test PR

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:  
  test:
    uses: Geode-solutions/actions/.github/workflows/cpp-test-pr.yml@master
    with:
      name: OPENGEODE
      directory: opengeode
    secrets: inherit
